# -*- coding: utf-8 -*-
"""Kcikit_learn_Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1agH31A1DloNFPVghMqPLjRwX3JwWO6GC
"""

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import pandas as pd

iris_dataset = load_iris()
iris_data = iris_dataset.data
print(iris_data)

fig, ax = plt.subplots()
scatter = ax.scatter(iris_data[:,0], iris_data[:,1], c=iris_dataset.target)
plt.show()

iris_df = pd.DataFrame(iris_data, columns=iris_dataset.feature_names)
pd.plotting.scatter_matrix(iris_df, c=iris_dataset.target)
plt.show()